kind: pipeline
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: node
  environment:
    HOST:
      from_secret: HostIP
  commands:
    - npm install
    - apt install docker -y
    - export DOCKER_HOST=tcp://${HOST}:2376
    - docker stack deploy --compose-file docker-compose.yml drone
