kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
image_pull_secrets:
- DockerToken

steps:
- name: test
  image: codeadmiral/cicdenvironment:latest
  environment:
    HOST:
      from_secret: HostIP
  commands:
    - npm install
    - apt install docker -y
    - export DOCKER_HOST=tcp://${HOST}:2376
    - podman stack deploy --compose-file docker-compose.yml drone
